version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medireminder_db
    environment:
      POSTGRES_DB: medireminder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"